#pragma once

#include <stdbool.h>
#include "ui_widget.h"   /* ui_event_t */

/* Forward-declare SDL_Event without pulling SDL.h into monoui code */
typedef union SDL_Event SDL_Event;

/* ─── Live key/state snapshot (for rendering visual indicators) ───────────── */

typedef struct {
    /* True while the corresponding key is held */
    bool key_enc_cw;    /* Right arrow / mouse-wheel up   */
    bool key_enc_ccw;   /* Left arrow  / mouse-wheel down */
    bool key_ok;        /* Space / Enter                   */
    bool key_back;      /* Escape                          */

    /* Set to true when an SDL event produced a ui_event_t.
       The caller should call sim_input_poll() to retrieve it.                  */
    bool event_pending;
} sim_input_state_t;

/* ─── API ─────────────────────────────────────────────────────────────────── */

/*  Reset all state.                                                            */
void sim_input_init(void);

/*  Feed one SDL event.  Updates internal state; may set event_pending.         */
void sim_input_process(const SDL_Event *e);

/*  If an event was generated by the last sim_input_process() call, copies it
 *  into *out and returns true.  Call once per frame (consumes one event).      */
bool sim_input_poll(ui_event_t *out);

/*  Read-only snapshot of current key states (for chrome rendering).            */
const sim_input_state_t *sim_input_state(void);
